---
- name: Ensure node_config_directory directory exists for user kolla
  file:
    path: "{{ node_config_directory }}"
    state: directory
    owner: "{{ kolla_user }}"
    group: "{{ kolla_group }}"
    mode: 0755
  become: True

- name: Get stat of libvirtd apparmor profile
  stat:
    path: /etc/apparmor.d/usr.sbin.libvirtd
  register: apparmor_libvirtd_profile
  when: ansible_facts.distribution == "Ubuntu"

- name: Get stat of libvirtd apparmor disable profile
  stat:
    path: /etc/apparmor.d/disable/usr.sbin.libvirtd
  register: apparmor_libvirtd_disable_profile
  when: ansible_facts.distribution == "Ubuntu"

- name: Remove apparmor profile for libvirt
  command: apparmor_parser -R /etc/apparmor.d/usr.sbin.libvirtd
  become: True
  when:
    - ansible_facts.distribution == "Ubuntu"
    - apparmor_libvirtd_profile.stat.exists
    - not apparmor_libvirtd_disable_profile.stat.exists
