---
- name: Set a fact to ensure Ansible uses the python interpreter in the virtualenv
  set_fact:
    ansible_python_interpreter: "{{ test_project_venv }}/bin/python"

- name: Ensure the test project exists
  os_project:
    auth_type: "{{ test_project_auth_type }}"
    auth: "{{ test_project_admin_auth }}"
    name: "{{ test_project_name }}"
    description: "{{ test_project_description }}"
    domain_id: "{{ test_project_domain }}"
    state: present
    enabled: True
    wait: yes
  environment: "{{ test_project_environment }}"

- name: Ensure test project users exist
  os_user:
    auth_type: "{{ test_project_auth_type }}"
    auth: "{{ test_project_admin_auth }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    default_project: "{{ test_project_name }}"
    domain: "{{ item.domain }}"
    state: present
    enabled: True
    wait: yes
  with_items: "{{ test_project_users }}"
  environment: "{{ test_project_environment }}"

- name: Ensure test project users have required roles
  os_user_role:
    auth_type: "{{ test_project_auth_type }}"
    auth: "{{ test_project_admin_auth }}"
    user: "{{ item.0.name }}"
    project: "{{ test_project_name }}"
    role: "{{ item.1 }}"
    state: present
  with_subelements:
    - "{{ test_project_users }}"
    - roles
  environment: "{{ test_project_environment }}"

- name: Ensure SSH keypairs are registered
  os_keypair:
    auth_type: "{{ test_project_auth_type }}"
    auth: "{{ test_project_auth }}"
    name: "{{ item.name }}"
    public_key_file: "{{ item.public_key_file | default(omit) }}"
    public_key: "{{ item.public_key | default(omit) }}"
    state: present
  with_items: "{{ test_project_keypairs }}"
  environment: "{{ test_project_environment }}"

# This variable is unset before we set it, and it does not appear to be
# possible to unset a variable in Ansible.
- name: Set a fact to reset the Ansible python interpreter
  set_fact:
    ansible_python_interpreter: /usr/bin/python

- name: Ensure openrc environment file exists
  local_action:
    module: template
    src: openrc.j2
    dest: "{{ item.openrc_file }}"
    mode: 0600
  with_items: "{{ test_project_users }}"
  when: "{{ item.openrc_file is defined }}"
