---
- name: Ensure the Kolla OpenStack configuration directores exist
  file:
    path: "{{ kolla_node_custom_config_path }}/{{ item.name }}"
    state: directory
    mode: 0750
  with_items:
    - { name: fluentd/output, enabled: "{{ kolla_extra_fluentd_output_path != None }}" }
    - { name: ironic, enabled: "{{ kolla_enable_ironic }}" }
    - { name: neutron, enabled: "{{ kolla_enable_neutron }}" }
    - { name: swift, enabled: "{{ kolla_enable_swift }}" }
  when: "{{ item.enabled | bool }}"

- name: Ensure the Kolla OpenStack configuration files exist
  template:
    src: "{{ item.src }}"
    dest: "{{ kolla_node_custom_config_path }}/{{ item.dest }}"
    mode: 0640
  with_items:
    - { src: glance.conf.j2, dest: glance.conf, enabled: "{{ kolla_enable_glance }}" }
    - { src: ironic.conf.j2, dest: ironic.conf, enabled: "{{ kolla_enable_ironic }}" }
    - { src: ironic-dnsmasq.conf.j2, dest: ironic/ironic-dnsmasq.conf, enabled: "{{ kolla_enable_ironic }}" }
    - { src: ironic-inspector.conf.j2, dest: ironic-inspector.conf, enabled: "{{ kolla_enable_ironic }}" }
    - { src: magnum.conf.j2, dest: magnum.conf, enabled: "{{ kolla_enable_magnum }}" }
    - { src: ml2_conf.ini.j2, dest: neutron/ml2_conf.ini, enabled: "{{ kolla_enable_neutron }}" }
    - { src: murano.conf.j2, dest: murano.conf, enabled: "{{ kolla_enable_murano }}" }
    - { src: neutron.conf.j2, dest: neutron.conf, enabled: "{{ kolla_enable_neutron }}" }
    - { src: nova.conf.j2, dest: nova.conf, enabled: "{{ kolla_enable_nova }}" }
    - { src: pxelinux.default.j2, dest: ironic/pxelinux.default, enabled: "{{ kolla_enable_ironic }}" }
    - { src: sahara.conf.j2, dest: sahara.conf, enabled: "{{ kolla_enable_sahara }}" }
  when: "{{ item.enabled | bool }}"

- name: Ensure extra fluentd output configuration files exist
  template:
    src: "{{ item }}"
    dest: "{{ kolla_node_custom_config_path }}/fluentd/output/{{ item | basename }}"
    mode: 0640
  with_fileglob:
    - "{{ kolla_extra_fluentd_output_path }}/*.conf"
  when: "{{ kolla_extra_fluentd_output_path != None }}"

- name: Ensure the ironic inspector kernel and ramdisk are downloaded
  get_url:
    url: "{{ item.url }}"
    dest: "{{ kolla_node_custom_config_path }}/ironic/{{ item.dest }}"
    mode: 0640
  with_items:
    - { url: "{{ kolla_inspector_ipa_kernel_upstream_url }}", dest: "ironic-agent.kernel" }
    - { url: "{{ kolla_inspector_ipa_ramdisk_upstream_url }}", dest: "ironic-agent.initramfs" }
  when:
    - kolla_enable_ironic | bool
    - item.url != None

- name: Ensure the ironic inspector kernel and ramdisk are copied
  copy:
    src: "{{ item.path }}"
    dest: "{{ kolla_node_custom_config_path }}/ironic/{{ item.dest }}"
    mode: 0640
  with_items:
    - { path: "{{ kolla_inspector_ipa_kernel_path }}", dest: "ironic-agent.kernel" }
    - { path: "{{ kolla_inspector_ipa_ramdisk_path }}", dest: "ironic-agent.initramfs" }
  when:
    - kolla_enable_ironic | bool
    - item.path != None
