---
# Path to a directory in which to create a virtualenv.
test_project_venv:

# Authentication type as used by os_* modules' 'auth_type' argument.
test_project_auth_type:

# Authentication options for admin as used by os_* modules' 'auth' argument.
test_project_admin_auth:

# Authentication option overrides for non-admin user as used by os_* modules'
# 'auth' argument.
test_project_user_auth_overrides:
  project_domain_name: "{{ test_project_domain }}"
  user_domain_name: "{{ test_project_users[0].domain }}"
  project_name: "{{ test_project_name }}"
  username: "{{ test_project_users[0].name }}"
  password: "{{ test_project_users[0].password }}"

# Authentication options for admin as used by os_* modules' 'auth' argument.
test_project_auth: "{{ test_project_admin_auth | combine(test_project_user_auth_overrides) }}"

# Environment variables for use with os_* modules.
test_project_environment:
  OS_IDENTITY_API_VERSION: 3

# Name of project to create.
test_project_name: test-project

# Description of project to create.
test_project_description: Test project

# Domain in which to create project.
test_project_domain: default

# List of users to create in the project.
test_project_users:
  - name: test-user
    password: test-password
    domain: default
    roles:
      - admin
    openrc_file: "{{ test_project_openrc_directory }}/test-user-openrc.sh"

# List of SSH key-pairs to register.
test_project_keypairs:
  - name: test-key
    public_key: "{{ test_project_public_key }}"

# SSH public key to register.
test_project_public_key:

# Directory in which to store openrc environment
test_project_openrc_directory: "{{ lookup('env', 'PWD') }}"
