---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure ironic inspector kernel and ramdisk image directory exists
      local_action:
        module: file
        path: "{{ item | dirname }}"
        state: directory
        recurse: True
      with_items:
        - "{{ kolla_inspector_ipa_kernel_path }}"
        - "{{ kolla_inspector_ipa_ramdisk_path }}"

    - name: Ensure ironic inspector kernel and ramdisk images exist
      local_action:
        module: file
        path: "{{ item }}"
        state: touch
      with_items:
        - "{{ kolla_inspector_ipa_kernel_path }}"
        - "{{ kolla_inspector_ipa_ramdisk_path }}"
