---
- name: Ensure the Kolla Ansible configuration directores exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0750
  become: True
  with_items:
    - "{{ kolla_config_path }}"
    - "{{ kolla_config_path }}/inventory"
    - "{{ kolla_node_custom_config_path }}"

- name: Ensure the Kolla configuration files exist
  template:
    src: "{{ item.src }}"
    dest: "{{ kolla_config_path }}/{{ item.dest }}"
    mode: 0640
  with_items:
    - { src: seed.j2, dest: inventory/seed }
    - { src: overcloud.j2, dest: inventory/overcloud }
    - { src: globals.yml.j2, dest: globals.yml }

- name: Ensure the Kolla passwords file exists
  kolla_passwords:
    src: "{{ kayobe_config_path }}/kolla/passwords.yml"
    dest: "{{ kayobe_config_path }}/kolla/passwords.yml"
    mode: 0640
    sample: "{{ kolla_ansible_install_dir }}/etc_examples/kolla/passwords.yml"
    overrides: "{{ kolla_ansible_custom_passwords }}"
    vault_password: "{{ kolla_ansible_vault_password }}"
    virtualenv: "{{ kolla_venv or omit }}"

- name: Ensure the Kolla passwords file is copied into place
  copy:
    src: "{{ kayobe_config_path }}/kolla/passwords.yml"
    dest: "{{ kolla_config_path }}/passwords.yml"
    remote_src: True
