---
- name: Ensure Kolla patches are applied
  patch:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: True
  with_items:
    - src: baremetal-docker_yum_repo.j2.patch
      dest: "{{ kolla_install_dir }}/ansible/roles/baremetal/templates/docker_yum_repo.j2"
    - src: baremetal-pre-install.yml.patch
      dest: "{{ kolla_install_dir }}/ansible/roles/baremetal/tasks/pre-install.yml"
    - src: ironic-api.json.j2.patch
      dest: "{{ kolla_install_dir }}/ansible/roles/ironic/templates/ironic-api.json.j2"
    - src: ironic-conductor.json.j2.patch
      dest: "{{ kolla_install_dir }}/ansible/roles/ironic/templates/ironic-conductor.json.j2"
    - src: prechecks-port_checks.yml.patch
      dest: "{{ kolla_install_dir }}/ansible/roles/prechecks/tasks/port_checks.yml"
    - src: kolla-ansible.patch
      dest: "{{ kolla_venv }}/bin/kolla-ansible"
