---
# Whether to enable a package repository for Docker.
enable_docker_repo: true

# Docker APT repository configuration.
docker_apt_url: "https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}"
docker_apt_repo: "deb {{ docker_apt_url }} {{ ansible_facts.distribution_release }} stable"
docker_apt_key_file: "gpg"
docker_apt_key_id: "0EBFCD88"
docker_apt_package: "docker-ce"

# Docker Yum repository configuration.
docker_yum_url: "https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}"
docker_yum_baseurl: "{{ docker_yum_url }}/$releasever/$basearch/stable"
docker_yum_gpgkey: "{{ docker_yum_url }}/gpg"
docker_yum_gpgcheck: true
docker_yum_package: "docker-ce"

customize_etc_hosts: True

kolla_user: "kolla"
kolla_group: "kolla"

# If true, the host firewall service (firewalld or ufw) will be disabled.
disable_firewall: True

docker_storage_driver: ""
docker_custom_option: ""
docker_custom_config: {}

docker_http_proxy: ""
docker_https_proxy: ""
docker_no_proxy: ""

# Version of python used to execute Ansible modules.
host_python_version: "{{ ansible_facts.python.version.major }}.{{ ansible_facts.python.version.minor }}"

debian_pkg_install:
 - "{{ docker_apt_package }}"
 - git
 - "python3-setuptools"
 - "python3-pip"
 - "{% if enable_multipathd|bool %}sg3-utils-udev{% endif %}"
 - "{% if not docker_disable_default_iptables_rules | bool %}iptables{% endif %}"

redhat_pkg_install:
 - "{{ docker_yum_package }}"
 - git
 - "python3-pip"
 - sudo
 - "{% if not docker_disable_default_iptables_rules | bool %}iptables{% endif %}"

ubuntu_pkg_removals:
 - lxd
 - lxc
 - libvirt-bin
 - open-iscsi

redhat_pkg_removals:
 - libvirt
 - libvirt-daemon
 - iscsi-initiator-utils

# From group_vars/all.yml:
docker_log_max_file: "5"
docker_log_max_size: "50m"
