---
- name: Ensure EPEL repo is installed
  yum:
    name: epel-release
    state: installed
  become: True

- name: Ensure required packages are installed
  yum:
    name: "{{ item }}"
    state: installed
  become: True
  with_items:
    - gcc
    - libffi-devel
    - openssl-devel
    - python-devel
    - python-pip
    - python-virtualenv

- name: Ensure source code checkout path exists
  file:
    path: "{{ source_checkout_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: True
  become: True

- name: Ensure Bifrost source code checkout exists
  git:
    repo: "{{ kolla_bifrost_source_url }}"
    dest: "{{ source_checkout_path }}/bifrost"
    version: "{{ kolla_bifrost_source_version }}"

- name: Ensure the latest version of pip is installed
  pip:
    name: "{{ item.name }}"
    state: latest
    virtualenv: "{{ kolla_bifrost_venv }}"
  with_items:
    - { name: pip }

- name: Ensure required Python packages are installed
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: present
    virtualenv: "{{ kolla_bifrost_venv }}"
  with_items:
    # Intall Bifrost from source.
    - name: "{{ source_checkout_path }}/bifrost"
    - name: shade
