---
# Note that setting this via a play or task variable seems to not
# evaluate the Jinja variable reference, so we use set_fact.
- name: Update the Ansible python interpreter fact to point to the virtualenv
  set_fact:
    ansible_python_interpreter: "{{ neutron_net_venv }}/bin/python"

- name: Ensure network is registered with Neutron
  os_network:
    auth_type: "{{ neutron_net_openstack_auth_type }}"
    auth: "{{ neutron_net_openstack_auth }}"
    name: "{{ neutron_net_name }}"
    provider_network_type: "{{ neutron_net_type | default(omit) }}"
    provider_physical_network: "{{ neutron_net_physical_network | default(omit) }}"
    provider_segmentation_id: "{{ neutron_net_segmentation_id | default(omit) }}"
    shared: "{{ neutron_net_shared }}"
    state: present

- name: Ensure subnet is registered with Neutron
  os_subnet:
    auth_type: "{{ neutron_net_openstack_auth_type }}"
    auth: "{{ neutron_net_openstack_auth }}"
    name: "{{ neutron_net_subnet_name }}"
    network_name: "{{ neutron_net_name }}"
    cidr: "{{ neutron_net_cidr }}"
    gateway_ip: "{{ neutron_net_gateway_ip | default(omit) }}"
    no_gateway_ip: "{{ not neutron_net_gateway_ip }}"
    allocation_pool_start: "{{ neutron_net_allocation_pool_start | default(omit) }}"
    allocation_pool_end: "{{ neutron_net_allocation_pool_end | default(omit) }}"
    state: present

# This variable is unset before we set it, and it does not appear to be
# possible to unset a variable in Ansible.
- name: Set a fact to reset the Ansible python interpreter
  set_fact:
    ansible_python_interpreter: /usr/bin/python
