---
# Note: Currently we install these using Yum to the system packages rather than
# pip to a virtualenv. This is because Yum is required elsewhere and cannot
# easily be installed in a virtualenv.
- name: Ensure package dependencies are installed
  local_action:
    module: yum
    name: "{{ item }}"
    state: installed
  become: True
  with_items:
    - python-netaddr
    - PyYAML

- name: Ensure IP addresses are allocated
  local_action:
    module: ip_allocation
    allocation_file: "{{ ip_allocation_filename }}"
    hostname: "{{ ip_allocation_hostname }}"
    net_name: "{{ item.net_name }}"
    cidr: "{{ item.cidr }}"
    allocation_pool_start: "{{ item.allocation_pool_start | default(omit) }}"
    allocation_pool_end: "{{ item.allocation_pool_end | default(omit) }}"
  with_items: "{{ ip_allocations }}"
