---
- name: Fail when the storage driver is invalid
  fail:
    msg: >
      Storage driver {{ docker_storage_driver }} is invalid. Valid drivers
      include 'devicemapper' and 'overlay'.
  when: docker_storage_driver not in ['devicemapper', 'overlay']

- name: Ensure user is in the docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  register: group_result
  become: True

# After adding the user to the docker group, we need to log out and in again to
# pick up the group membership. We do this by removing the SSH ControlPersist
# connection.
- name: Drop the persistent SSH connection to activate the new group membership
  local_action:
    module: shell ssh -O stop {{ cp_hostname }} -o ControlPath={{ cp_path }}
  register: socket_removal
  failed_when:
    - socket_removal|failed
    - "'No such file or directory' not in socket_removal.stderr"
  with_items: "{{ play_hosts }}"
  run_once: True
  when: group_result|changed
  vars:
    cp_hostname: "{{ hostvars[item].ansible_host|default(inventory_hostname) }}"
    cp_username: "{{ hostvars[item].ansible_user }}"
    cp_port: "{{ hostvars[item].ansible_ssh_port|default('22') }}"
    cp_path: "~/.ansible/cp/ansible-ssh-{{ cp_hostname }}-{{ cp_port }}-{{ cp_username }}"

- name: Ensure Docker daemon is started
  service:
    name: docker
    state: started
  become: True

- name: Check whether docker storage is in loopback mode
  command: docker info
  register: docker_info
  changed_when: False

- name: Fail when loopback-mode containers or images exist
  fail:
    msg: >
      Not configuring docker storage in {{ docker_storage_driver }} mode as
      loopback-backed containers or images exist.
  when:
    - "{{ 'Data loop file' in docker_info.stdout }}"
    - "{{ 'Images: 0' not in docker_info.stdout }}"
    - "{{ 'Containers: 0' not in docker_info.stdout }}"

- include: storage.yml
  when: "{{ 'Data loop file' in docker_info.stdout }}"

- include: config.yml
