---
- name: Ensure user is in the docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: True

- name: Check whether docker storage is in loopback mode
  command: docker info
  register: docker_info
  changed_when: False
  become: True

- name: Fail when loopback-mode containers or images exist
  fail:
    msg: >
      Not configuring docker storage in direct-lvm mode as loopback-backed
      containers or images exist.
  when:
    - "{{ 'Data loop file' in docker_info.stdout }}"
    - "{{ 'Images: 0' not in docker_info.stdout }}"
    - "{{ 'Containers: 0' not in docker_info.stdout }}"

- include: storage.yml
  when: "{{ 'Data loop file' in docker_info.stdout }}"

- name: Read Docker daemon config file
  slurp:
    src: /etc/docker/daemon.json
  register: docker_daemon_conf
  become: True

- name: Parse Docker daemon config JSON
  set_fact:
    docker_daemon_json: "{{ docker_daemon_conf['content'] | b64decode | from_json }}"

- include: config.yml
  when: "{{ docker_daemon_json['mtu'] }} != 1450 or {{ docker_daemon_json['storage-driver'] }} != 'devicemapper'"
