---
- include: dell-compute-node-inventory.yml

- name: Ensure compute nodes are PXE booted
  hosts: compute
  gather_facts: no
  vars:
    delegate_host: "{{ groups['controllers'][0] }}"
  tasks:
    - name: Ensure ipmitool is installed
      yum:
        name: ipmitool
        state: installed
      become: True
      run_once: True
      delegate_to: "{{ item }}"
      with_items:
        - "{{ hostvars[delegate_host].ansible_host }}"

    - name: Ensure compute nodes are powered off
      command: ipmitool -U {{ ipmi_username }} -P {{ ipmi_password }} -H {{ ipmi_address }} -I lanplus chassis power off
      delegate_to: "{{ item }}"
      with_items:
        - "{{ hostvars[delegate_host].ansible_host }}"

    - name: Pause to prevent overwhelming BMCs
      pause:
        seconds: 5

    - name: Ensure compute nodes are set to boot via PXE
      command: ipmitool -U {{ ipmi_username }} -P {{ ipmi_password }} -H {{ ipmi_address }} -I lanplus chassis bootdev pxe
      delegate_to: "{{ item }}"
      with_items:
        - "{{ hostvars[delegate_host].ansible_host }}"

    - name: Pause to prevent overwhelming BMCs
      pause:
        seconds: 5

    - name: Ensure compute nodes are powered on
      command: ipmitool -U {{ ipmi_username }} -P {{ ipmi_password }} -H {{ ipmi_address }} -I lanplus chassis power on
      delegate_to: "{{ item }}"
      with_items:
        - "{{ hostvars[delegate_host].ansible_host }}"
