---
# Set the boot mode (BIOS, UEFI) of Dell compute nodes.

# Add compute nodes to the Ansible inventory.
- include: dell-compute-node-boot-mode.yml

- name: Ensure compute nodes boot mode is set
  hosts: compute
  gather_facts: no
  vars:
    # Set this to the required boot mode. One of 'bios' or 'uefi'.
    drac_boot_mode: "bios"
  roles:
    - role: ssh-known-host
    - role: drac-boot-mode
