---
# Configure the compute nodes to PXE boot.

# Add compute nodes to the Ansible inventory.
- include: dell-compute-node-inventory.yml

- name: Ensure compute nodes are PXE booted
  hosts: compute
  gather_facts: no
  vars:
    # Set this to the index of the inteface on which to enable PXE.
    drac_pxe_interface: 1
    # Set this to a list of indices of all interfaces.
    drac_pxe_all_interfaces: [1, 2, 3, 4]
  roles:
    - role: ssh-known-host
    - role: drac-pxe
