---
# Deploy/pull/reconfigure/upgrade Docker registry.
#
# Follows kolla-ansible service deployment patterns.
#
# Variables:
# action: One of deploy, destroy, pull, reconfigure, upgrade

- name: Ensure a local Docker registry is deployed
  hosts: controllers[0]
  roles:
    - role: docker-registry
