---
- name: Ensure external network and subnet are registered in neutron
  # Only required to run on a single host.
  hosts: controllers[0]
  roles:
    - role: stackhpc.os-networks
      os_networks_venv: "{{ virtualenv_path }}/shade"
      os_networks_openstack_auth_type: "{{ openstack_auth_type }}"
      os_networks_openstack_auth: "{{ openstack_auth }}"
      # Network configuration.
      os_networks_name: "{{ external_net_name }}"
      os_networks_type: "{% if external_net_name | net_vlan %}vlan{% else %}flat{% endif %}"
      os_networks_physical_network: "physnet1"
      os_networks_segmentation_id: "{{ external_net_name | net_vlan }}"
      os_networks_shared: True
      os_networks_external: True
      # Subnet configuration.
      os_networks_subnet_name: "{{ external_net_name }}"
      os_networks_cidr: "{{ external_net_name | net_cidr }}"
      os_networks_gateway_ip: "{{ external_net_name | net_gateway }}"
      os_networks_allocation_pool_start: "{{ external_net_name | net_neutron_allocation_pool_start }}"
      os_networks_allocation_pool_end: "{{ external_net_name | net_neutron_allocation_pool_end }}"
