---
- name: Ensure IP addresses are allocated
  hosts: controllers
  gather_facts: no
  pre_tasks:
    - set_fact:
        ip_allocations: "{{ ip_allocations|default([]) + [{'net_name': item, 'cidr': item|net_cidr}] }}"
      with_items: "{{ network_interfaces }}"
  roles:
    - role: ip-allocation
      ip_allocation_filename: "{{ kayobe_config_path }}/network-allocation.yml"
      ip_allocation_hostname: "{{ inventory_hostname }}"
