---
- name: Ensure Ironic Python Agent (IPA) images are downloaded and registered
  hosts: controllers[0]
  pre_tasks:
    - name: Validate OpenStack password authentication parameters
      fail:
        msg: >
          Required OpenStack authentication parameter {{ item }} is
          {% if item in openstack_auth %}empty{% else %}not present{% endif %}
          in openstack_auth. Have you sourced the environment file?
      when:
        - "{{ openstack_auth_type == 'password' }}"
        - "{{ item not in openstack_auth or not openstack_auth[item] }}"
      with_items: "{{ openstack_auth_password_required_params }}"
      tags:
        - config-validation

  roles:
    - role: ipa-images
      ipa_images_venv: "{{ ansible_env['PWD'] }}/shade-venv"
      ipa_images_openstack_auth_type: "{{ openstack_auth_type }}"
      ipa_images_openstack_auth: "{{ openstack_auth }}"
      ipa_images_cache_path: "{{ image_cache_path }}"
