---
- name: Ensure the power and management network switches are configured
  hosts: mgmt-switches
  gather_facts: no
  vars:
    provider:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      transport: cli
      authorize: yes
      auth_pass: "{{ switch_auth_pass }}"
  tasks:
    - name: Ensure switch interfaces are configured
      local_action:
        module: dellos6_config
        provider: "{{ provider }}"
        lines: >
          {{ ['description ' ~ item.value.description] +
             item.value.config | default([]) }}
        parents:
          - "interface {{ item.key }}"
      with_dict: "{{ switch_interface_config }}"
