---
- name: Ensure networking is configured
  hosts: seed-hypervisor:seed:overcloud
  tags:
    - config
    - network
  vars:
    ether_interfaces: "{{ network_interfaces | net_select_ethers | list }}"
    bridge_interfaces: "{{ network_interfaces | net_select_bridges | list }}"
    bond_interfaces: "{{ network_interfaces | net_select_bonds | list }}"
  pre_tasks:
    - block:
        - name: Validate network interface configuration
          fail:
            msg: >
              Network interface validation failed - no interface configured for
              {{ item }}. This should be configured via '{{ item }}_interface'.
          with_items: "{{ ether_interfaces }}"
          when: not item | net_interface

        - name: Validate bridge interface configuration
          fail:
            msg: >
              Bridge interface validation failed - no interface configured for
              {{ item }}. This should be configured via '{{ item }}_interface'.
          with_items: "{{ bridge_interfaces }}"
          when: not item | net_interface

        - name: Validate bond interface configuration
          fail:
            msg: >
              Bond interface validation failed - no interface configured for
              {{ item }}. This should be configured via '{{ item }}_interface'.
          with_items: "{{ bond_interfaces }}"
          when: not item | net_interface
      tags:
        - config-validation

    - name: Ensure NetworkManager is disabled
      service:
        name: NetworkManager
        state: stopped
        enabled: no
      become: True
      register: nm_result
      failed_when:
        - nm_result is failed
        # Ugh, Ansible's service module doesn't handle uninstalled services.
        - "'Could not find the requested service' not in nm_result.msg"

  roles:
    - role: ahuffman.resolv
      when: resolv_is_managed | bool
      become: True

    - role: MichaelRigart.interfaces
      interfaces_route_tables: "{{ network_route_tables }}"
      interfaces_ether_interfaces: >
        {{ ether_interfaces |
           map('net_interface_obj') |
           list }}
      interfaces_bridge_interfaces: >
        {{ bridge_interfaces |
           map('net_bridge_obj') |
           list }}
      interfaces_bond_interfaces: >
        {{ bond_interfaces |
           map('net_bond_obj') |
           list }}

# Configure virtual ethernet patch links to connect the workload provision
# and external network bridges to the Neutron OVS bridge.
- name: Ensure OVS patch links exist
  hosts: network:compute
  tags:
    - config
    - network
  tasks:
    - import_role:
        name: veth
      vars:
        veth_interfaces: "{{ network_interfaces | net_ovs_veths }}"
