---
- name: Save overcloud service configuration
  hosts: overcloud
  vars:
    # Override this to change the directory in which the configuration will be
    # saved.
    config_save_path: "{{ lookup('env', 'PWD') ~ '/overcloud-config' }}"
  tasks:
    - name: Find overcloud service configuration files
      find:
        paths: "/etc/kolla"
        recurse: True
      register: find_result

    - name: Save overcloud service configuration
      fetch:
        src: "{{ item.path }}"
        dest: "{{ config_save_path }}"
      with_items: "{{ find_result.files }}"
