---
# Deploy/pull/reconfigure/upgrade overcloud services not managed by
# kolla-ansible.
#
# Follows kolla-ansible service deployment patterns.
#
# Variables:
# action: One of deploy, pull, reconfigure, upgrade

- include: docker-registry.yml
- include: opensm.yml
