---
# Generate an environment file for interacting with the public OpenStack APIs
# as the admin user in the admin project.

- name: Ensure a public OpenStack API environment file exists
  hosts: config-mgmt
  vars:
    external_api_proto: "{% if kolla_enable_tls_external | bool %}https{% else %}http{% endif %}"
    external_api_vip_address: "{{ external_net_name | net_vip_address }}"
    external_api_keystone_port: 5000
  roles:
    - role: public-openrc
      public_openrc_kolla_config_path: "{{ kolla_config_path }}"
      public_openrc_auth_url: "{{ external_api_proto }}://{{ external_api_vip_address }}:{{ external_api_keystone_port }}"
