---
- src: ahuffman.resolv
- src: jriguera.configdrive
- src: MichaelRigart.interfaces
- src: mrlesmithjr.manage-lvm
- src: resmo.ntp
- src: stackhpc.drac
- src: stackhpc.drac-facts
- src: stackhpc.os-flavors
- src: stackhpc.os-networks
- src: stackhpc.os-projects
- src: yatesr.timezone
