---
- src: ahuffman.resolv
- src: jriguera.configdrive
# Use our fork until the VLAN and MTU fix PRs are merged.
#- src: MichaelRigart.interfaces
- src: https://github.com/stackhpc/ansible-role-interfaces
  version: support-mtu
  name: MichaelRigart.interfaces
- src: mrlesmithjr.manage-lvm
- src: resmo.ntp
- src: stackhpc.drac
- src: stackhpc.drac-facts
- src: yatesr.timezone
