---
# Directory where Kolla custom configuration files will be installed.
kolla_node_custom_config_path:

###############################################################################
# Ironic configuration.

# List of enabled Ironic drivers.
ironic_drivers:
  - agent_ssh
  - agent_ipmitool
  - pxe_ssh
  - pxe_ipmitool

# Free form extra configuration to append to ironic.conf.
kolla_extra_ironic:

###############################################################################
# Ironic inspector configuration.

# Whether inspector should manage the firewall.
kolla_inspector_manage_firewall:

# Comma-separated list of inspector processing plugins.
kolla_inspector_processing_hooks:

# Which MAC addresses to add as ports during introspection. One of 'all',
# 'active' or 'pxe'.
kolla_inspector_port_addition:

# Whether to enable discovery of nodes not managed by Ironic.
kolla_inspector_enable_discovery:

# The Ironic driver with which to register newly discovered nodes.
kolla_inspector_discovery_enroll_node_driver:

# List of extra kernel parameters for the inspector default PXE configuration.
kolla_inspector_extra_kernel_options:

# URL of Ironic Python Agent (IPA) kernel image for Ironic Inspector.
kolla_inspector_ipa_kernel_upstream_url:

# URL of Ironic Python Agent (IPA) ramdisk image for Ironic Inspector.
kolla_inspector_ipa_ramdisk_upstream_url:

# Free form extra configuration to append to ironic-inspector.conf.
kolla_extra_inspector:

###############################################################################
# Ironic inspector dnsmasq configuration.

# Start of range of IP addresses for dnsmasq to allocate from.
kolla_inspector_dhcp_pool_start:

# End of range of IP addresses for dnsmasq to allocate from.
kolla_inspector_dhcp_pool_end:

###############################################################################
# Glance configuration.

# Free form extra configuration to append to glance-api.conf and
# glance-registry.conf.
kolla_extra_glance:
