---
- project:
    templates:
      - build-openstack-sphinx-docs
      - docs-on-readthedocs
      - openstack-cover-jobs
      - openstack-python35-jobs
      - openstack-python-jobs
    vars:
      rtd_webhook_id: '50407'
    check:
      jobs:
        - build-openstack-releasenotes
        - kayobe-tox-ansible-syntax
        # NOTE(priteau): issues with python-pip-whl installation on xenial
        - kayobe-tox-ansible:
            voting: false
        - kayobe-tox-molecule
        - kayobe-overcloud-centos
        # NOTE(priteau): depends on a working stable/queens CI
        - kayobe-overcloud-upgrade-centos:
            voting: false
        - kayobe-seed-centos
        # NOTE(priteau): depends on a working stable/queens CI
        - kayobe-seed-upgrade-centos:
            voting: false

    gate:
      queue: kayobe
      jobs:
        - build-openstack-releasenotes
        - kayobe-tox-ansible-syntax
        # NOTE(priteau): issues with python-pip-whl installation on xenial
        # - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-centos
        # NOTE(priteau): depends on a working stable/queens CI
        # - kayobe-overcloud-upgrade-centos
        - kayobe-seed-centos
        # NOTE(priteau): depends on a working stable/queens CI
        # - kayobe-seed-upgrade-centos
