---
- project:
    templates:
      - openstack-cover-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-centos
        - kayobe-overcloud-upgrade-centos
        - kayobe-seed-centos
        - kayobe-seed-upgrade-centos

    gate:
      queue: kayobe
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-centos
        - kayobe-overcloud-upgrade-centos
        - kayobe-seed-centos
        - kayobe-seed-upgrade-centos
