---
- project:
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py27
        - openstack-tox-py35
        - build-openstack-sphinx-docs
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-overcloud-centos

    gate:
      queue: kayobe
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py27
        - openstack-tox-py35
        - build-openstack-sphinx-docs
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-overcloud-centos
