---
- project:
    templates:
      - build-openstack-sphinx-docs
      - docs-on-readthedocs
      - openstack-cover-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python-jobs
    vars:
      rtd_webhook_id: '50407'
    check:
      jobs:
        - build-openstack-releasenotes
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-centos
        - kayobe-overcloud-upgrade-centos
        - kayobe-seed-centos
        - kayobe-seed-upgrade-centos

    gate:
      queue: kayobe
      jobs:
        - build-openstack-releasenotes
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-centos
        - kayobe-overcloud-upgrade-centos
        - kayobe-seed-centos
        - kayobe-seed-upgrade-centos

    post:
      jobs:
        - trigger-readthedocs-webhook:
            vars:
              rtd_project_name: kayobe-release-notes
              rtd_webhook_id: '74820'
    pre-release:
      jobs:
        - trigger-readthedocs-webhook:
            vars:
              rtd_project_name: kayobe-release-notes
              rtd_webhook_id: '74820'
    release:
      jobs:
        - trigger-readthedocs-webhook:
            vars:
              rtd_project_name: kayobe-release-notes
              rtd_webhook_id: '74820'
