---
- project:
    templates:
      - openstack-cover-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-centos8
        # TODO(mgoddard): Enable upgrade jobs when CentOS 8 support in Train.
        # - kayobe-overcloud-upgrade-centos8
        - kayobe-seed-centos8
        # TODO(mgoddard): Enable upgrade jobs when CentOS 8 support in Train.
        # - kayobe-seed-upgrade-centos8

    gate:
      queue: kayobe
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-centos8
        # TODO(mgoddard): Enable upgrade jobs when CentOS 8 support in Train.
        # - kayobe-overcloud-upgrade-centos8
        - kayobe-seed-centos8
        # TODO(mgoddard): Enable upgrade jobs when CentOS 8 support in Train.
        # - kayobe-seed-upgrade-centos
