---
- name: Ensure the Kolla configuration directores exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0750
  become: True
  with_items:
    - "{{ kolla_config_path }}"
