---
- name: Ensure required packages are installed
  yum:
    name: "{{ item }}"
    state: installed
  become: True
  with_items:
    - gcc
    - libffi-devel
    - openssl-devel
    - patch
    - python-devel
    - python-pip
    - python-virtualenv

- name: Ensure the latest version of pip is installed
  pip:
    name: "{{ item.name }}"
    state: latest
    virtualenv: "{{ kolla_venv }}"
  with_items:
    - { name: pip }

- name: Ensure required Python packages are installed
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
    virtualenv: "{{ kolla_venv }}"
  with_items:
    - { name: kolla, version: "{{ kolla_openstack_release }}" }
    # Required for kolla-genpwd.
    - { name: PyYAML, version: "3.12" }

- name: Ensure the Kolla configuration directores exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  become: True
  with_items:
    - "{{ kolla_config_path }}"
